"""Fixed, user-facing UI strings in uk/pl/ru/en.

Agent answers are generated by the LLM in the user's language (SPEC §5.3)
and do not go through this module. This module is only for the small set
of fixed strings used by commands/keyboards.
"""

from __future__ import annotations

SUPPORTED_LANGUAGES = ("uk", "pl", "ru", "en")
DEFAULT_LANGUAGE = "en"

_STRINGS: dict[str, dict[str, str]] = {
    "help_text": {
        "en": (
            "I'm your Paperless-ngx assistant.\n\n"
            "/search <text> — full-text search\n"
            "/recent [n] — latest documents\n"
            "/doc <id> — document card\n"
            "/inbox — documents in your inbox\n"
            "/expiring [days] — documents expiring soon\n"
            "/usage — today's AI usage\n"
            "/clear — reset assistant memory\n\n"
            "Send me a document or photo to upload it, or just ask a question "
            "about your archive."
        ),
        "uk": (
            "Я ваш асистент Paperless-ngx.\n\n"
            "/search <текст> — повнотекстовий пошук\n"
            "/recent [n] — останні документи\n"
            "/doc <id> — картка документа\n"
            "/inbox — документи у вхідних\n"
            "/expiring [днів] — документи, що скоро закінчуються\n"
            "/usage — витрати на AI сьогодні\n"
            "/clear — очистити пам'ять асистента\n\n"
            "Надішліть документ або фото, щоб завантажити його, або просто "
            "задайте питання про ваш архів."
        ),
        "pl": (
            "Jestem Twoim asystentem Paperless-ngx.\n\n"
            "/search <tekst> — wyszukiwanie pełnotekstowe\n"
            "/recent [n] — ostatnie dokumenty\n"
            "/doc <id> — karta dokumentu\n"
            "/inbox — dokumenty w skrzynce\n"
            "/expiring [dni] — dokumenty wygasające wkrótce\n"
            "/usage — dzisiejsze zużycie AI\n"
            "/clear — wyczyść pamięć asystenta\n\n"
            "Wyślij dokument lub zdjęcie, aby je przesłać, albo zadaj pytanie "
            "o swoje archiwum."
        ),
        "ru": (
            "Я ваш ассистент Paperless-ngx.\n\n"
            "/search <текст> — полнотекстовый поиск\n"
            "/recent [n] — последние документы\n"
            "/doc <id> — карточка документа\n"
            "/inbox — документы во входящих\n"
            "/expiring [дней] — документы, срок которых скоро истекает\n"
            "/usage — расход AI за сегодня\n"
            "/clear — очистить память ассистента\n\n"
            "Отправьте документ или фото, чтобы загрузить его, либо просто "
            "задайте вопрос об архиве."
        ),
    },
    "search_usage": {
        "en": "Usage: /search <text>",
        "uk": "Використання: /search <текст>",
        "pl": "Użycie: /search <tekst>",
        "ru": "Использование: /search <текст>",
    },
    "no_results": {
        "en": "No documents found.",
        "uk": "Документів не знайдено.",
        "pl": "Nie znaleziono dokumentów.",
        "ru": "Документы не найдены.",
    },
    "doc_not_found": {
        "en": "Document #{id} not found.",
        "uk": "Документ #{id} не знайдено.",
        "pl": "Nie znaleziono dokumentu #{id}.",
        "ru": "Документ #{id} не найден.",
    },
    "doc_usage": {
        "en": "Usage: /doc <id>",
        "uk": "Використання: /doc <id>",
        "pl": "Użycie: /doc <id>",
        "ru": "Использование: /doc <id>",
    },
    "field_created": {
        "en": "Created",
        "uk": "Створено",
        "pl": "Utworzono",
        "ru": "Создан",
    },
    "field_correspondent": {
        "en": "Correspondent",
        "uk": "Контрагент",
        "pl": "Korespondent",
        "ru": "Контрагент",
    },
    "field_type": {
        "en": "Type",
        "uk": "Тип",
        "pl": "Typ",
        "ru": "Тип",
    },
    "field_tags": {
        "en": "Tags",
        "uk": "Теги",
        "pl": "Tagi",
        "ru": "Теги",
    },
    "field_link": {
        "en": "Open in Paperless",
        "uk": "Відкрити в Paperless",
        "pl": "Otwórz w Paperless",
        "ru": "Открыть в Paperless",
    },
    "generic_error": {
        "en": "Something went wrong talking to Paperless. Please try again.",
        "uk": "Сталася помилка під час звернення до Paperless. Спробуйте ще раз.",
        "pl": "Wystąpił błąd podczas kontaktu z Paperless. Spróbuj ponownie.",
        "ru": "Произошла ошибка при обращении к Paperless. Попробуйте ещё раз.",
    },
    "page_indicator": {
        "en": "Page {page}/{pages}",
        "uk": "Сторінка {page}/{pages}",
        "pl": "Strona {page}/{pages}",
        "ru": "Страница {page}/{pages}",
    },
}


def resolve_language(telegram_language_code: str | None) -> str:
    if not telegram_language_code:
        return DEFAULT_LANGUAGE
    primary = telegram_language_code.split("-")[0].lower()
    if primary in SUPPORTED_LANGUAGES:
        return primary
    return DEFAULT_LANGUAGE


def t(key: str, lang: str, **kwargs: object) -> str:
    strings = _STRINGS.get(key)
    if strings is None:
        raise KeyError(f"unknown i18n key: {key}")
    template = strings.get(lang) or strings[DEFAULT_LANGUAGE]
    return template.format(**kwargs) if kwargs else template
