"""Fixed, user-facing UI strings in uk/pl/ru/en.

Agent answers are generated by the LLM in the user's language (SPEC §5.3)
and do not go through this module. This module is only for the small set
of fixed strings used by commands/keyboards.
"""

from __future__ import annotations

SUPPORTED_LANGUAGES = ("uk", "pl", "ru", "en")
DEFAULT_LANGUAGE = "en"

_STRINGS: dict[str, dict[str, str]] = {
    "help_text": {
        "en": (
            "I'm your Paperless-ngx assistant.\n\n"
            "/search <text> — full-text search\n"
            "/recent [n] — latest documents\n"
            "/doc <id> — document card\n"
            "/inbox — documents in your inbox\n"
            "/expiring [days] — documents expiring soon\n"
            "/usage — today's AI usage\n"
            "/clear — reset assistant memory\n\n"
            "Send me a document or photo to upload it, or just ask a question "
            "about your archive."
        ),
        "uk": (
            "Я ваш асистент Paperless-ngx.\n\n"
            "/search <текст> — повнотекстовий пошук\n"
            "/recent [n] — останні документи\n"
            "/doc <id> — картка документа\n"
            "/inbox — документи у вхідних\n"
            "/expiring [днів] — документи, що скоро закінчуються\n"
            "/usage — витрати на AI сьогодні\n"
            "/clear — очистити пам'ять асистента\n\n"
            "Надішліть документ або фото, щоб завантажити його, або просто "
            "задайте питання про ваш архів."
        ),
        "pl": (
            "Jestem Twoim asystentem Paperless-ngx.\n\n"
            "/search <tekst> — wyszukiwanie pełnotekstowe\n"
            "/recent [n] — ostatnie dokumenty\n"
            "/doc <id> — karta dokumentu\n"
            "/inbox — dokumenty w skrzynce\n"
            "/expiring [dni] — dokumenty wygasające wkrótce\n"
            "/usage — dzisiejsze zużycie AI\n"
            "/clear — wyczyść pamięć asystenta\n\n"
            "Wyślij dokument lub zdjęcie, aby je przesłać, albo zadaj pytanie "
            "o swoje archiwum."
        ),
        "ru": (
            "Я ваш ассистент Paperless-ngx.\n\n"
            "/search <текст> — полнотекстовый поиск\n"
            "/recent [n] — последние документы\n"
            "/doc <id> — карточка документа\n"
            "/inbox — документы во входящих\n"
            "/expiring [дней] — документы, срок которых скоро истекает\n"
            "/usage — расход AI за сегодня\n"
            "/clear — очистить память ассистента\n\n"
            "Отправьте документ или фото, чтобы загрузить его, либо просто "
            "задайте вопрос об архиве."
        ),
    },
    "search_usage": {
        "en": "Usage: /search <text>",
        "uk": "Використання: /search <текст>",
        "pl": "Użycie: /search <tekst>",
        "ru": "Использование: /search <текст>",
    },
    "no_results": {
        "en": "No documents found.",
        "uk": "Документів не знайдено.",
        "pl": "Nie znaleziono dokumentów.",
        "ru": "Документы не найдены.",
    },
    "doc_not_found": {
        "en": "Document #{id} not found.",
        "uk": "Документ #{id} не знайдено.",
        "pl": "Nie znaleziono dokumentu #{id}.",
        "ru": "Документ #{id} не найден.",
    },
    "doc_usage": {
        "en": "Usage: /doc <id>",
        "uk": "Використання: /doc <id>",
        "pl": "Użycie: /doc <id>",
        "ru": "Использование: /doc <id>",
    },
    "field_created": {
        "en": "Created",
        "uk": "Створено",
        "pl": "Utworzono",
        "ru": "Создан",
    },
    "field_correspondent": {
        "en": "Correspondent",
        "uk": "Контрагент",
        "pl": "Korespondent",
        "ru": "Контрагент",
    },
    "field_type": {
        "en": "Type",
        "uk": "Тип",
        "pl": "Typ",
        "ru": "Тип",
    },
    "field_tags": {
        "en": "Tags",
        "uk": "Теги",
        "pl": "Tagi",
        "ru": "Теги",
    },
    "field_link": {
        "en": "Open in Paperless",
        "uk": "Відкрити в Paperless",
        "pl": "Otwórz w Paperless",
        "ru": "Открыть в Paperless",
    },
    "generic_error": {
        "en": "Something went wrong talking to Paperless. Please try again.",
        "uk": "Сталася помилка під час звернення до Paperless. Спробуйте ще раз.",
        "pl": "Wystąpił błąd podczas kontaktu z Paperless. Spróbuj ponownie.",
        "ru": "Произошла ошибка при обращении к Paperless. Попробуйте ещё раз.",
    },
    "page_indicator": {
        "en": "Page {page}/{pages}",
        "uk": "Сторінка {page}/{pages}",
        "pl": "Strona {page}/{pages}",
        "ru": "Страница {page}/{pages}",
    },
    "upload_success": {
        "en": "✅ Added #{id}: {title}\n{link}\n\nOCR + classification will run in background.",
        "uk": "✅ Додано #{id}: {title}\n{link}\n\nOCR і класифікація виконаються у фоні.",
        "pl": "✅ Dodano #{id}: {title}\n{link}\n\nOCR i klasyfikacja wykonają się w tle.",
        "ru": "✅ Добавлено #{id}: {title}\n{link}\n\nOCR и классификация выполнятся в фоне.",
    },
    "upload_success_no_id": {
        "en": "✅ Document added. OCR + classification will run in background.",
        "uk": "✅ Документ додано. OCR і класифікація виконаються у фоні.",
        "pl": "✅ Dokument dodany. OCR i klasyfikacja wykonają się w tle.",
        "ru": "✅ Документ добавлен. OCR и классификация выполнятся в фоне.",
    },
    "upload_duplicate": {
        "en": "Already in Paperless as #{id}.\n{link}",
        "uk": "Вже є в Paperless як #{id}.\n{link}",
        "pl": "Już jest w Paperless jako #{id}.\n{link}",
        "ru": "Уже есть в Paperless как #{id}.\n{link}",
    },
    "upload_duplicate_generic": {
        "en": "This looks like a duplicate of a document already in Paperless.",
        "uk": "Схоже, це дублікат документа, який вже є в Paperless.",
        "pl": "Wygląda na duplikat dokumentu już istniejącego w Paperless.",
        "ru": "Похоже, это дубликат документа, который уже есть в Paperless.",
    },
    "upload_failed": {
        "en": "Upload failed: {error}",
        "uk": "Завантаження не вдалося: {error}",
        "pl": "Przesyłanie nie powiodło się: {error}",
        "ru": "Загрузка не удалась: {error}",
    },
    "upload_timeout": {
        "en": "Still processing after 5 minutes — check Paperless later.",
        "uk": "Досі обробляється через 5 хвилин — перевірте Paperless пізніше.",
        "pl": "Wciąż przetwarzane po 5 minutach — sprawdź Paperless później.",
        "ru": "Всё ещё обрабатывается после 5 минут — проверьте Paperless позже.",
    },
    "file_too_large": {
        "en": "File is too large for Telegram. Open it in Paperless instead:\n{link}",
        "uk": "Файл надто великий для Telegram. Відкрийте його в Paperless:\n{link}",
        "pl": "Plik jest za duży dla Telegrama. Otwórz go w Paperless:\n{link}",
        "ru": "Файл слишком большой для Telegram. Откройте его в Paperless:\n{link}",
    },
    "budget_reached": {
        "en": "Daily AI budget reached. Commands still work: "
        "/search, /recent, /doc, /inbox, /expiring.",
        "uk": "Денний бюджет AI витрачено. Команди працюють: "
        "/search, /recent, /doc, /inbox, /expiring.",
        "pl": "Dzienny budżet AI wykorzystany. Komendy wciąż działają: "
        "/search, /recent, /doc, /inbox, /expiring.",
        "ru": "Дневной бюджет AI исчерпан. Команды работают: "
        "/search, /recent, /doc, /inbox, /expiring.",
    },
    "memory_cleared": {
        "en": "Assistant memory cleared for this chat.",
        "uk": "Пам'ять асистента для цього чату очищено.",
        "pl": "Pamięć asystenta dla tego czatu wyczyszczona.",
        "ru": "Память ассистента для этого чата очищена.",
    },
    "usage_today": {
        "en": "Today: ${cost:.4f} / ${budget:.2f}",
        "uk": "Сьогодні: ${cost:.4f} / ${budget:.2f}",
        "pl": "Dzisiaj: ${cost:.4f} / ${budget:.2f}",
        "ru": "Сегодня: ${cost:.4f} / ${budget:.2f}",
    },
    "usage_history_header": {
        "en": "Last 7 days:",
        "uk": "Останні 7 днів:",
        "pl": "Ostatnie 7 dni:",
        "ru": "Последние 7 дней:",
    },
    "expiring_usage": {
        "en": "Usage: /expiring [days]",
        "uk": "Використання: /expiring [днів]",
        "pl": "Użycie: /expiring [dni]",
        "ru": "Использование: /expiring [дней]",
    },
    "inbox_done": {
        "en": "Removed from inbox.",
        "uk": "Видалено з вхідних.",
        "pl": "Usunięto ze skrzynki.",
        "ru": "Удалено из входящих.",
    },
    "rel_today": {
        "en": "today",
        "uk": "сьогодні",
        "pl": "dzisiaj",
        "ru": "сегодня",
    },
    "rel_in_days": {
        "en": "in {n} days",
        "uk": "через {n} дн.",
        "pl": "za {n} dni",
        "ru": "через {n} дн.",
    },
    "rel_expired_days_ago": {
        "en": "expired {n} days ago",
        "uk": "минув {n} дн. тому",
        "pl": "minęło {n} dni temu",
        "ru": "истёк {n} дн. назад",
    },
    "reminder_header": {
        "en": "📅 Document expiry reminder",
        "uk": "📅 Нагадування про закінчення документів",
        "pl": "📅 Przypomnienie o wygasających dokumentach",
        "ru": "📅 Напоминание о сроках действия документов",
    },
    "menu_help": {
        "en": "Show help",
        "uk": "Показати довідку",
        "pl": "Pokaż pomoc",
        "ru": "Показать справку",
    },
    "menu_search": {
        "en": "Search documents",
        "uk": "Пошук документів",
        "pl": "Szukaj dokumentów",
        "ru": "Поиск документов",
    },
    "menu_recent": {
        "en": "Recently added documents",
        "uk": "Останні додані документи",
        "pl": "Ostatnio dodane dokumenty",
        "ru": "Последние добавленные документы",
    },
    "menu_doc": {
        "en": "Show a document by id",
        "uk": "Показати документ за id",
        "pl": "Pokaż dokument po id",
        "ru": "Показать документ по id",
    },
    "menu_inbox": {
        "en": "Documents waiting in your inbox",
        "uk": "Документи у вхідних",
        "pl": "Dokumenty w skrzynce",
        "ru": "Документы во входящих",
    },
    "menu_expiring": {
        "en": "Documents expiring soon",
        "uk": "Документи, що скоро закінчуються",
        "pl": "Dokumenty wygasające wkrótce",
        "ru": "Документы, срок которых скоро истекает",
    },
    "menu_usage": {
        "en": "Today's AI usage",
        "uk": "Витрати на AI сьогодні",
        "pl": "Dzisiejsze zużycie AI",
        "ru": "Расход AI за сегодня",
    },
    "menu_clear": {
        "en": "Reset assistant memory",
        "uk": "Очистити пам'ять асистента",
        "pl": "Wyczyść pamięć asystenta",
        "ru": "Очистить память ассистента",
    },
    "search_prompt": {
        "en": "What would you like to search for?",
        "uk": "Що шукати?",
        "pl": "Czego szukać?",
        "ru": "Что искать?",
    },
    "doc_prompt": {
        "en": "Which document id?",
        "uk": "Який id документа?",
        "pl": "Jakie id dokumentu?",
        "ru": "Какой id документа?",
    },
    "cancelled": {
        "en": "Cancelled.",
        "uk": "Скасовано.",
        "pl": "Anulowano.",
        "ru": "Отменено.",
    },
    "inbox_rename_prompt": {
        "en": "Send the new title for #{id}:",
        "uk": "Надішліть нову назву для #{id}:",
        "pl": "Wyślij nowy tytuł dla #{id}:",
        "ru": "Отправьте новое название для #{id}:",
    },
    "inbox_renamed": {
        "en": "Title updated.",
        "uk": "Назву оновлено.",
        "pl": "Tytuł zaktualizowany.",
        "ru": "Название обновлено.",
    },
}


def resolve_language(telegram_language_code: str | None) -> str:
    if not telegram_language_code:
        return DEFAULT_LANGUAGE
    primary = telegram_language_code.split("-")[0].lower()
    if primary in SUPPORTED_LANGUAGES:
        return primary
    return DEFAULT_LANGUAGE


def t(key: str, lang: str, **kwargs: object) -> str:
    strings = _STRINGS.get(key)
    if strings is None:
        raise KeyError(f"unknown i18n key: {key}")
    template = strings.get(lang) or strings[DEFAULT_LANGUAGE]
    return template.format(**kwargs) if kwargs else template
